# Generated by Django 5.1 on 2024-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
