# Generated by Django 5.1 on 2024-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_listmodel_date_listmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
